#:schema https://json.schemastore.org/alacritty.json

[general]
import = ["~/.config/alacritty/themes/themes/everforest_dark.toml"]
live_config_reload = true

[font]
normal = { family = "JetBrainsMono Nerd Font" }
bold = { family = "JetBrainsMono Nerd Font", style = "Medium" }
italic = { family = "MonaspiceRn Nerd Font", style = "Medium Italic"}
bold_italic = { family = "MonaspiceRn Nerd Font", style = "Bold Italic" }
size = 14

# builtin_box_drawing = true
offset = { x = 0, y = 2 }
glyph_offset = { x = 0, y = 2 }

[colors]
draw_bold_text_with_bright_colors = true

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 1
padding = { x = 10, y = 10 }
dynamic_padding = true
blur = true

[window.class]
general = "Alacrity"

[window.dimensions]
columns = 120
lines = 30

[cursor.style]
blinking = "On"

[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[mouse]
hide_when_typing = true
