#:schema https://json.schemastore.org/alacritty.json

[general]
import = ["~/.config/alacritty/themes/themes/solarized_dark.toml"]

[font]
size = 15
offset = { x = 0, y = 2 }

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Regular Italic"

#
[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 0.97
padding = { x = 2, y = 2 }
dynamic_padding = true
blur = true

[window.class]
general = "Alacrity"

[window.dimensions]
columns = 120
lines = 30

[cursor.style]
blinking = "On"

[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[mouse]
hide_when_typing = true
